// Package wireguard generates wg syncconf configurations for tunnels.
package wireguard

import (
	"fmt"
	"strings"

	"router/pkg/models"
)

// IfaceName normalizes the interface name for a tunnel.
func IfaceName(name string) string {
	if strings.HasPrefix(name, "wg") {
		return name
	}
	return "wg-" + name
}

// GenerateConf renders an ini document for `wg syncconf <iface> -`.
func GenerateConf(t models.WireGuardTunnel) (string, error) {
	var b strings.Builder
	b.WriteString("# Generated by routerd. Do not edit.\n[Interface]\n")
	fmt.Fprintf(&b, "PrivateKey = %s\n", t.PrivateKey)
	port := t.ListenPort
	if port == 0 {
		port = 51820
	}
	fmt.Fprintf(&b, "ListenPort = %d\n", port)
	for _, p := range t.Peers {
		if p.PublicKey == "" {
			continue
		}
		b.WriteString("\n[Peer]\n")
		if p.Name != "" {
			fmt.Fprintf(&b, "# %s\n", p.Name)
		}
		fmt.Fprintf(&b, "PublicKey = %s\n", p.PublicKey)
		if len(p.AllowedIPs) > 0 {
			fmt.Fprintf(&b, "AllowedIPs = %s\n", strings.Join(p.AllowedIPs, ", "))
		}
		if p.Endpoint != "" {
			fmt.Fprintf(&b, "Endpoint = %s\n", p.Endpoint)
		}
		if p.PersistentKeepalive > 0 {
			fmt.Fprintf(&b, "PersistentKeepalive = %d\n", p.PersistentKeepalive)
		}
	}
	return b.String(), nil
}

// Mask returns a copy safe for API responses (private keys never exposed).
func Mask(t models.WireGuardTunnel) models.WireGuardTunnel {
	if t.PrivateKey != "" {
		t.PrivateKey = "***"
	}
	return t
}
