// Package firewall generates deterministic nftables scripts from the
// declarative configuration (design §14-§16). The web/CLI/API never touch
// nftables directly; everything flows through here.
package firewall

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"net/netip"
	"sort"
	"strings"

	"router/pkg/models"
)

// ZoneSet returns the nft set name for a firewall zone.
func ZoneSet(zone string) string {
	return strings.ToLower(zone) + "_ifaces"
}

type gen struct{ b strings.Builder }

func (g *gen) line(ind int, format string, args ...any) {
	g.b.WriteString(strings.Repeat("\t", ind))
	fmt.Fprintf(&g.b, format, args...)
	g.b.WriteString("\n")
}

// Generate produces a complete, self-contained inet router nftables script.
func Generate(c models.Config) (string, error) {
	var wanIfaces []string
	for _, w := range c.WANs {
		if w.IsEnabled() {
			wanIfaces = append(wanIfaces, w.Interface)
		}
	}

	zones := map[string][]string{} // zone -> interfaces (ordered, deduped)
	trusted := map[string]bool{}
	for _, n := range c.Networks {
		add := true
		for _, x := range zones[n.Zone] {
			if x == n.Interface {
				add = false
			}
		}
		if add {
			zones[n.Zone] = append(zones[n.Zone], n.Interface)
		}
		if n.CanAccessLAN() && strings.EqualFold(n.Zone, "LAN") {
			trusted[n.Zone] = true
		}
	}
	for _, t := range c.WireGuard {
		z := t.Zone
		if z == "" {
			z = "VPN"
		}
		zones[z] = append(zones[z], wgIface(t.Name))
		trusted[z] = true
	}
	// Rules may reference zones that currently have no networks (e.g. an
	// orphaned rule after a network delete). Declare those sets empty so the
	// generated ruleset always validates.
	for _, r := range c.FirewallRules {
		for _, z := range []string{r.SourceZone, r.DestZone} {
			if z != "" && strings.ToUpper(z) != "WAN" {
				if _, ok := zones[strings.ToUpper(z)]; !ok {
					zones[strings.ToUpper(z)] = nil
				}
			}
		}
	}

	hasPF := false
	for _, pf := range c.PortForwards {
		if pf.Enabled {
			hasPF = true
		}
	}

	g := &gen{}
	g.line(0, "#!/usr/sbin/nft -f")
	g.line(0, "# Generated by routerd — manual edits will be overwritten.")
	g.line(0, "table inet router {")
	g.line(1, `set wan_ifaces { type ifname; flags dynamic; elements = { %s } }`, quotedList(wanIfaces))
	for _, z := range zoneOrder(c, zones) {
		if len(zones[z]) == 0 {
			g.line(1, "set %s { type ifname; }", ZoneSet(z))
			continue
		}
		g.line(1, "set %s { type ifname; elements = { %s } }", ZoneSet(z), quotedList(zones[z]))
	}
	if hasPF {
		g.line(1, `set wan_public { type ipv4_addr; flags dynamic,timeout; timeout 1 hour }`)
	}
	g.b.WriteString("\n")

	// --- input ---
	g.line(1, "chain input { comment \"__ROUTERD_SHA__\"")
	g.line(2, "type filter hook input priority 0; policy drop;")
	g.line(2, `iifname "lo" accept`)
	// DHCP replies are accepted BEFORE ct-invalid-drop: a request sent to
	// the limited broadcast address is often not conntracked, so the server
	// reply would otherwise be classified INVALID and silently dropped.
	g.line(2, `iifname @wan_ifaces udp sport 67 udp dport 68 accept`)
	g.line(2, "ct state established,related accept")
	g.line(2, "ct state invalid drop")
	g.line(2, `iifname @wan_ifaces ip6 nexthdr 58 accept`)
	for _, t := range c.WireGuard {
		port := t.ListenPort
		if port == 0 {
			port = 51820
		}
		g.line(2, `meta l4proto udp th dport %d counter accept comment "wireguard %s"`, port, t.Name)
	}
	g.line(2, `iifname != @wan_ifaces icmp type echo-request accept`)
	g.line(2, `iifname != @wan_ifaces ip6 nexthdr icmpv6 accept`)
	g.line(2, `iifname != @wan_ifaces udp dport { 53, 67, 547 } accept`)
	g.line(2, `iifname != @wan_ifaces tcp dport 53 accept`)
	g.line(2, "iifname @wan_ifaces counter drop")
	g.line(1, "}")
	g.b.WriteString("\n")

	// --- forward ---
	g.line(1, "chain forward {")
	g.line(2, "type filter hook forward priority 0; policy drop;")
	g.line(2, "ct state established,related accept")
	g.line(2, "ct state invalid drop")
	g.line(2, "iifname @wan_ifaces counter drop")
	for _, r := range c.FirewallRules {
		if !r.Enabled {
			continue
		}
		g.line(2, "%s", ruleLine(r))
	}
	for _, n := range c.Networks {
		zs := ZoneSet(n.Zone)
		if trusted[n.Zone] || n.CanAccessLAN() {
			g.line(2, "iifname @%s oifname @wan_ifaces counter accept", zs)
		} else if n.HasInternet() {
			g.line(2, "iifname @%s oifname @wan_ifaces counter accept", zs)
		}
	}
	// trusted zones may reach all other zones
	for zn := range trusted {
		for zo := range zones {
			if zn == zo || strings.EqualFold(zo, "WAN") {
				continue
			}
			g.line(2, "iifname @%s oifname @%s counter accept", ZoneSet(zn), ZoneSet(zo))
		}
	}
	// explicit access_to_lan grants
	for _, n := range c.Networks {
		if n.CanAccessLAN() && !trusted[n.Zone] {
			g.line(2, "iifname @%s oifname @lan_ifaces counter accept", ZoneSet(n.Zone))
		}
	}
	g.line(2, `counter limit rate 10/second log prefix "router-fwd-drop: " drop`)
	g.line(1, "}")
	g.b.WriteString("\n")

	// --- dstnat ---
	g.line(1, "chain dstnat {")
	g.line(2, "type nat hook prerouting priority dstnat; policy accept;")
	for _, pf := range c.PortForwards {
		if !pf.Enabled {
			continue
		}
		target := pf.InternalIP
		if pf.InternalPort != 0 {
			target = fmt.Sprintf("%s:%d", pf.InternalIP, pf.InternalPort)
		}
		guard := `iifname @wan_ifaces`
		if w, ok := findWAN(c, pf.WAN); ok && w.IsEnabled() {
			guard = fmt.Sprintf("iifname %q", w.Interface)
		}
		comment := pf.Name
		if comment == "" {
			comment = pf.ID
		}
		g.line(2, `%s %s dport %d dnat to %s comment "%s"`, guard, pf.Protocol, pf.ExternalPort, target, comment)
		g.line(2, `iifname != @wan_ifaces ip daddr @wan_public %s dport %d dnat to %s`, pf.Protocol, pf.ExternalPort, target)
	}
	g.line(1, "}")
	g.b.WriteString("\n")

	// --- srcnat ---
	g.line(1, "chain postrouting {")
	g.line(2, "type nat hook postrouting priority srcnat; policy accept;")
	for _, n := range c.Networks {
		if !n.HasInternet() {
			continue
		}
		pfx, err := netip.ParsePrefix(n.Subnet)
		if err != nil {
			continue
		}
		for _, w := range c.WANs {
			if !w.IsEnabled() {
				continue
			}
			g.line(2, `ip saddr %s oifname %q counter masquerade`, pfx.Masked().String(), w.Interface)
		}
	}
	g.line(1, "}")
	g.line(0, "}")
	script := g.b.String()
	sum := sha256.Sum256([]byte(script))
	hexHash := hex.EncodeToString(sum[:8])
	script = strings.ReplaceAll(script, "__ROUTERD_SHA__", "routerd-sha:"+hexHash)
	marker := "# routerd-sha:" + hexHash + "\n"
	return marker + script, nil
}

func wgIface(name string) string {
	if strings.HasPrefix(name, "wg") {
		return name
	}
	return "wg-" + name
}

func ruleLine(r models.FirewallRule) string {
	var sb strings.Builder
	sb.WriteString("iifname @" + ZoneSet(r.SourceZone))
	sb.WriteString(" oifname @" + ZoneSet(r.DestZone))
	if len(r.Source) > 0 {
		sb.WriteString(" ip saddr { " + strings.Join(r.Source, ", ") + " }")
	}
	if len(r.Destination) > 0 {
		sb.WriteString(" ip daddr { " + strings.Join(r.Destination, ", ") + " }")
	}
	if r.Protocol == "tcp" || r.Protocol == "udp" {
		sb.WriteString(" " + r.Protocol + " dport " + ports(r.Ports))
	} else if r.Protocol == "icmp" {
		sb.WriteString(" meta l4proto icmp")
	}
	sb.WriteString(" counter")
	switch r.Action {
	case models.ActionAccept:
		sb.WriteString(" accept")
	case models.ActionDrop:
		sb.WriteString(" drop")
	case models.ActionReject:
		sb.WriteString(" reject")
	case models.ActionLog:
		sb.WriteString(` limit rate 10/second log prefix "fwrule " drop`)
	}
	if r.Name != "" {
		sb.WriteString(` comment "` + r.Name + `"`)
	}
	return sb.String()
}

func ports(ps []models.PortRange) string {
	var parts []string
	for _, p := range ps {
		if p.End == 0 || p.End == p.Start {
			parts = append(parts, fmt.Sprint(p.Start))
		} else {
			parts = append(parts, fmt.Sprintf("%d-%d", p.Start, p.End))
		}
	}
	if len(ps) == 0 {
		return "0-65535"
	}
	if len(parts) == 1 {
		return parts[0]
	}
	return "{ " + strings.Join(parts, ", ") + " }"
}

func quotedList(xs []string) string {
	var parts []string
	for _, x := range xs {
		parts = append(parts, fmt.Sprintf("%q", x))
	}
	return strings.Join(parts, ", ")
}

// zoneOrder lists zone names deterministically: config network order, then
// any remaining (e.g. wireguard) zones sorted alphabetically.
func zoneOrder(c models.Config, zones map[string][]string) []string {
	var out []string
	seen := map[string]bool{}
	for _, n := range c.Networks {
		if !seen[n.Zone] {
			seen[n.Zone] = true
			out = append(out, n.Zone)
		}
	}
	var rest []string
	for z := range zones {
		if !seen[z] {
			rest = append(rest, z)
		}
	}
	sort.Strings(rest)
	return append(out, rest...)
}

func findWAN(c models.Config, name string) (models.WAN, bool) {
	for _, w := range c.WANs {
		if w.Name == name || w.ID == name {
			return w, true
		}
	}
	return models.WAN{}, false
}
