// Package dhcp generates configuration for the managed DHCP/DNS service
// (dnsmasq) and exposes lease state. routerd orchestrates the service; it
// does not reimplement it (design §17, §52).
package dhcp

import (
	"fmt"
	"net/netip"
	"sort"
	"strings"

	"router/pkg/models"
)

// ConfigDir is where generated dnsmasq configuration is written.
const ConfigDir = "/etc/dnsmasq.d"

// ConfPath is the generated router config drop-in.
const ConfPath = "/etc/dnsmasq.d/router.conf"

// LeaseFilePath returns the dnsmasq lease file location.
func LeaseFilePath() string {
	if p := confDirOverride["leases"]; p != "" {
		return p
	}
	return "/var/lib/misc/dnsmasq.leases"
}

var confDirOverride = map[string]string{}

// SetPaths allows the daemon to relocate files (dev/test environments).
func SetPaths(confPath, leasePath string) {
	confDirOverride["conf"] = confPath
	confDirOverride["leases"] = leasePath
}

// ConfPathFor returns the effective config path.
func ConfPathFor() string {
	if p := confDirOverride["conf"]; p != "" {
		return p
	}
	return ConfPath
}

// GenerateDnsmasqConf renders the complete dnsmasq configuration.
func GenerateDnsmasqConf(c models.Config) (string, error) {
	var b strings.Builder
	b.WriteString("# Generated by routerd. Do not edit.\n")
	b.WriteString("addn-hosts=/etc/hosts\nstrict-order\ndomain-needed\nbogus-priv\ndhcp-authoritative\nno-resolv\n")
	b.WriteString("localise-queries\nexpand-hosts\n")
	if c.DNS.ListenPort != 0 && c.DNS.ListenPort != 53 {
		fmt.Fprintf(&b, "port=%d\n", c.DNS.ListenPort)
	}
	upstreams := c.DNS.Upstreams
	if len(upstreams) == 0 {
		upstreams = []string{"1.1.1.1", "8.8.8.8"}
	}
	for _, u := range upstreams {
		fmt.Fprintf(&b, "server=%s\n", dnsServerArg(u))
	}

	var ifaces []string
	for _, n := range c.Networks {
		ifaces = append(ifaces, n.Interface)
	}
	sort.Strings(ifaces)
	for _, i := range ifaces {
		fmt.Fprintf(&b, "interface=%s\n", i)
	}
	fmt.Fprintf(&b, "bind-interfaces\n")
	// Loopback is excluded: stub resolvers (systemd-resolved, WSL) commonly
	// own :53 on lo, and this service answers on LAN interfaces only.
	fmt.Fprintf(&b, "except-interface=lo\n")

	for _, n := range c.Networks {
		if !n.DHCP.Enabled {
			fmt.Fprintf(&b, "no-dhcp-interface=%s\n", n.Interface)
			continue
		}
		pfx, err := netip.ParsePrefix(n.Subnet)
		if err != nil {
			return "", fmt.Errorf("network %s: %w", n.Name, err)
		}
		gw := pfx.Addr().String()
		lease := n.DHCP.LeaseSeconds
		if lease == 0 {
			lease = 86400
		}
		fmt.Fprintf(&b, "dhcp-range=%s,%s,%s,%d\n", n.Name, n.DHCP.Start, n.DHCP.End, lease)
		fmt.Fprintf(&b, "dhcp-option=tag:%s,3,%s\n", n.Name, gw)
		dnsList := n.DHCP.DNS
		if len(dnsList) == 0 {
			dnsList = []string{gw}
		}
		fmt.Fprintf(&b, "dhcp-option=tag:%s,6,%s\n", n.Name, strings.Join(dnsList, ","))
		// untagged fallbacks (keep simple option forms for compatibility)
		fmt.Fprintf(&b, "dhcp-option=3,%s\n", gw)
		fmt.Fprintf(&b, "dhcp-option=6,%s\n", strings.Join(dnsList, ","))
		for _, r := range n.DHCP.Reservations {
			if r.Name != "" {
				fmt.Fprintf(&b, "dhcp-host=%s,%s,%s\n", r.MAC, r.Name, r.IP)
			} else {
				fmt.Fprintf(&b, "dhcp-host=%s,%s\n", r.MAC, r.IP)
			}
		}
		if n.IPv6RA && n.IPv6Subnet != "" {
			if p6, err := netip.ParsePrefix(n.IPv6Subnet); err == nil {
				fmt.Fprintf(&b, "dhcp-range=%s,slaac\n", p6.Masked().Addr().String())
				fmt.Fprintf(&b, "ra-param=%s,high,600,120\n", n.Interface)
			}
		}
	}

	for _, r := range c.DNS.LocalRecords {
		fmt.Fprintf(&b, "address=/%s/%s\n", r.Name, r.IP)
	}
	// DHCP hostname registrations
	for _, n := range c.Networks {
		for _, r := range n.DHCP.Reservations {
			if r.Name != "" {
				fmt.Fprintf(&b, "address=/%s.%s/%s\n", r.Name, "router.local", r.IP)
			}
		}
	}
	return b.String(), nil
}

func dnsServerArg(u string) string {
	if i := strings.LastIndex(u, ":"); i > 0 && !strings.Contains(u[i+1:], "]") && strings.Count(u, ":") == 1 {
		host, port := u[:i], u[i+1:]
		if _, err := netip.ParseAddr(host); err == nil {
			return host + "#" + port
		}
	}
	return u
}

// UnitFile returns a dedicated systemd unit so routerd does not fight the
// distribution's dnsmasq unit/config combination.
func UnitFile(confPath string) string {
	return `[Unit]
Description=routerd managed DHCP/DNS (dnsmasq)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/sbin/dnsmasq -k --conf-file=` + confPath + `
Restart=on-failure
RestartSec=2

[Install]
WantedBy=multi-user.target
`
}

// ServiceName is the systemd unit routerd manages for DHCP/DNS.
const ServiceName = "routerd-dnsmasq"
